name: Deploy portfolio into Lightsail
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to Lightsail on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      - name: SSH into Lightsail and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_SSH_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.LIGHTSAIL_SSH_PORT }}
          script: |
            cd kushal_website
            ./script/deploy.sh